services:
  - type: web
    name: official-cars-v2
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_SECRET
        sync: false
