const express=require('express');const cors=require('cors');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const app=express();app.use(cors());app.use(express.json({limit:'10mb'}));const PORT=process.env.PORT||10000;const ADMIN_SECRET=process.env.ADMIN_SECRET||'';const DB=path.join(__dirname,'data.json');
function read(){return JSON.parse(fs.readFileSync(DB,'utf8'))}function write(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}function hash(v){return crypto.createHash('sha256').update(v).digest('hex')}
function auth(req,res,next){const token=req.headers.authorization?.replace('Bearer ','');if(!ADMIN_SECRET||token===hash(ADMIN_SECRET))return next();res.status(401).json({error:'Unauthorized'})}
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'admin.html')));
app.get('/health',(req,res)=>res.json({ok:true,service:'official-cars-api',time:new Date().toISOString()}));
app.get('/api/public',(req,res)=>{const d=read();res.json({dealers:d.dealers,vehicles:d.vehicles})});
app.post('/api/admin/login',(req,res)=>{if(!ADMIN_SECRET)return res.status(503).json({error:'Set ADMIN_SECRET in Render Environment Variables first'});if(req.body.password!==ADMIN_SECRET)return res.status(401).json({error:'Wrong password'});res.json({token:hash(ADMIN_SECRET)})});
app.get('/api/admin/data',auth,(req,res)=>res.json(read()));
app.put('/api/admin/data',auth,(req,res)=>{if(!req.body||!Array.isArray(req.body.dealers)||!Array.isArray(req.body.vehicles))return res.status(400).json({error:'Expected dealers and vehicles arrays'});write(req.body);res.json({ok:true,counts:{dealers:req.body.dealers.length,vehicles:req.body.vehicles.length}})});
app.post('/api/admin/import-json',auth,(req,res)=>{let incoming=req.body;if(incoming?.data)incoming=incoming.data;if(!incoming||!Array.isArray(incoming.vehicles))return res.status(400).json({error:'Invalid inventory JSON'});let d=read();const dealers=incoming.dealers||[];for(const x of dealers){const i=d.dealers.findIndex(a=>a.id===x.id);if(i>=0)d.dealers[i]=x;else d.dealers.push(x)}for(const v of incoming.vehicles){const i=d.vehicles.findIndex(a=>a.id===v.id);if(i>=0)d.vehicles[i]={...d.vehicles[i],...v};else d.vehicles.push(v)}write(d);res.json({ok:true,counts:{dealers:d.dealers.length,vehicles:d.vehicles.length}})});
app.get('/api/admin/export',auth,(req,res)=>{res.setHeader('Content-Disposition','attachment; filename="official-cars-backup.json"');res.type('application/json').send(JSON.stringify(read(),null,2))});
app.listen(PORT,'0.0.0.0',()=>console.log(`Official Cars API listening on ${PORT}`));